### PR TITLE
pisa

### PR DESCRIPTION
**Pull request by seanmacavaney**
Adding [PISA](https://github.com/pisa-engine/pisa) to the mix!

I haven't tested all the evaluations exhaustively on Kaggle yet, but it looks like it can provide pretty substantial speedups on as datasets get larger, likely due to its dynamic pruning.

QPS (PISA are my measurements on Kaggle, others are from the README)

Single Thread:

| Dataset | Query QPS | Index DPS |
|-----|-----|-----|
| `arguana` | 128.01 | 3608.75 |
| `climate-fever` | 25.66 | 5474.84 |
| `cqadupstack` | 281.65 | 4380.73 |
| `dbpedia-entity` | 114.05 | 9532.44 |
| `fever` | 60.76 | 5633.20 |
| `fiqa` | 546.61 | 4655.99 |
| `hotpotqa` | 39.70 | 10199.26 |
| `msmarco` | 125.18 | 9873.08 |
| `nfcorpus` | 2639.38 | 2484.47 |
| `nq` | 117.34 | 6923.50 |
| `quora` | 528.45 | 37954.43 |
| `scidocs` | 678.06 | 3076.90 |
| `scifact` | 1100.60 | 2560.91 |
| `trec-covid` | 140.92 | 4736.72 |
| `webis-touche2020` | 201.19 | 2301.53 |

Multi-Thread:

| Dataset | Query QPS | Index DPS |
|-----|-----|-----|
| `arguana` | 311.00 | 3523.65 |
| `climate-fever` | 69.89 | 9034.65 |
| `cqadupstack` | 694.82 | 6587.47 |
| `dbpedia-entity` | 294.66 | 14742.73 |
| `fever` | 166.77 | 9156.45 |
| `fiqa` | 1240.22 | 4539.39 |
| `hotpotqa` | 109.44 | 15827.75 |
| `msmarco` | 340.29 | 16117.84 |
| `nfcorpus` | 3188.22 | 2506.77 |
| `nq` | 312.09 | 11571.51 |
| `quora` | 1534.93 | 73437.22 |
| `scidocs` | 1461.20 | 3127.49 |
| `scifact` | 2620.73 | 1695.45 |
| `trec-covid` | 268.96 | 4687.50 |
| `webis-touche2020` | 297.79 | 3317.11 |

Notebooks: 
 - [NQ](https://www.kaggle.com/smac2048/pisa-nq)
 - [dppedia-entity](https://www.kaggle.com/code/smac2048/pisa-dbpedia-entity)
 - [climate-fever](https://www.kaggle.com/code/smac2048/pisa-climate-fever)
 - [hotpotqa](https://www.kaggle.com/code/smac2048/pisa-hotpotqa/notebook)
 - [fever](https://www.kaggle.com/code/smac2048/pisa-fever)
 - [msmarco](https://www.kaggle.com/code/smac2048/pisa-msmarco)
 - [cqadupstack](https://www.kaggle.com/code/smac2048/pisa-cqadupstack)
 - [remainder](https://www.kaggle.com/code/smac2048/pisa-rest)

<details>
<summary>Expand for Kaggle notebook code to run</summary>

```
!git clone https://github.com/seanmacavaney/bm25-benchmarks
%cd bm25-benchmarks
%pip install -r requirements-pisa.txt
%env JAVA_HOME=/usr/lib/jvm/default-java/
!python -m benchmark.on_pisa -d msmarco
```

</details>

### CODE REVIEW

**Comment by xhluca** [comment]
Thanks! Will merge once the kaggle results are out (you can add the link in the readme, there's a section for kaggle links. one notebook is fine if you don't want to run them individually).

Btw can you set n_threads=1? It seems to be -1 by default, but the result table assume n_threads=1 to be fair to single-threaded implementations (rank-bm25 for example). 

You can also set n_threads=-1 in this folded table right below the single-threaded results:

image

**Comment by xhluca** [comment]
aside: 100 q/s on msmarco is crazy. I can't believe we are seeing <10ms query time on 8M docs on free kaggle cpus🤯

**Comment by seanmacavaney** [comment]
> (you can add the link in the readme, there's a section for kaggle links. one notebook is fine if you don't want to run them individually).

👍 on it!

> Btw can you set n_threads=1? It seems to be -1 by default, but the result table assume n_threads=1 to be fair to single-threaded implementations (rank-bm25 for example).

Thanks! It looks like that was only just the default for [`build_pisa_index`](https://github.com/xhluca/bm25-benchmarks/pull/3/files#diff-c7c3e42266c16bddf1df037e4d49f926c4d8e0310fb1b413b99b64f760c9a4dfR32), the [script's default arguments](https://github.com/xhluca/bm25-benchmarks/pull/3/files#diff-c7c3e42266c16bddf1df037e4d49f926c4d8e0310fb1b413b99b64f760c9a4dfR162-R167) are correct. I'll update it there too though.

> You can also set n_threads=-1 in this folded table right below the single-threaded results

👍 Nice, I missed that table before! Will add.

> aside: 100 q/s on msmarco is crazy. I can't believe we are seeing <10ms query time on 8M docs on free kaggle cpus🤯

Yep 🤓, I usually get <= 1ms/q (single-threaded) on msmarco on the machines I use for research, which is exactly why I use PISA :)

**Comment by xhluca** [comment]
Ah makes sense! Pisa looks very good. I wonder how they can achieve such a high throughput on the top-k selection step (which is a big bottleneck). Perhaps it's really worth looking into inverted indexing!

**Comment by seanmacavaney** [comment]
The software includes a lot of optimizations, but my understanding is that dynamic pruning with [BlockMaxWAND](https://dl.acm.org/doi/10.1145/2009916.2010048) is one of the most impactful techniques it implements.

**Comment by seanmacavaney** [comment]
@xhluca all results done -- I merged them into the README tables

**Comment by xhluca** [comment]
Awesome, merged!

**Comment by xhluca** [comment]
@seanmacavaney I'm trying to add results for recalll@1000 and ndcg@10. It seems that output for this is not present: https://www.kaggle.com/code/smac2048/pisa-cqadupstack/notebook

Could you add a cp to move the json results to the /kaggle/working/?

**Comment by seanmacavaney** [comment]
Yep, no problem! Running now

**Pull request merged**
